### ISSUE TITLE
CanvasRenderService is not a constructor

### ISSUE THREAD

**Issue by SurgicalCrow** [SeanSobey/ChartjsNodeCanvas#65]
```
 const { CanvasRenderSerice } = require("chartjs-node-canvas")
 
       const canvasRenderService = new CanvasRenderService(
           width,
           height,
           ChartJS => {}
        );
```

With error:

```
5|x | (node:18303) UnhandledPromiseRejectionWarning: TypeError: CanvasRenderService is not a constructor
5|x |     at Client.<anonymous> (/root/covid/bot.js:357:37)
5|x |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by SeanSobey** [comment]
Sorry for the delay and any inconvenience, a fix has been pushed. For details see #60.
