### ISSUE TITLE
Error with chartjs-plugin-datalabels and pie chart

### ISSUE THREAD

**Issue by arahiko-ayami** [SeanSobey/ChartjsNodeCanvas#79]
Hi, I'm using your package combine with chartjs and chartjs-plugin-datalabels
`
    "chart.js": "2.9.4",
    "chartjs-node-canvas": "^3.2.0",
    "chartjs-plugin-datalabels": "^1.0.0",
`

My code:
```Javascript	
const caseData = {
labels: ['Deaths', 'Recovered', 'Active'],
datasets: [{
	data: [
		deaths,
		recovered,
		active,
	],
	backgroundColor: [
		'rgb(255, 99, 132)',
		'rgb(54, 162, 235)',
		'rgb(153, 102, 255)',
	],
	datalabels:{
		backgroundColor: function(context) {
			return context.dataset.backgroundColor
		},
		borderColor: 'white',
		borderRadius: 25,
		borderWidth: 2,
		color: 'white',
		display: function(context) {
			const dataset = context.dataset
			const count = dataset.data.length
			const value = dataset.data[context.dataIndex]
			return value > count * 1.5
		},
		font: {
			weight: 'bold',
			size: 17,
		},
		padding: 6,
		formatter: function(value, context) {
			const percentage = calculatePercentage(value, cases)
			return `${percentage}%`
		},
		anchor: function(context) {
			return calculatePercentage(context.dataset.data[context.dataIndex], cases) > 3 ? 'center' : 'end'
		},
	},
}],
}

const configChartJS = {
type: 'pie',
data: caseData,
options: {
	layout:{
		padding: {
			top: 30,
			left: 30,
			right: 30,
		},
	},
	legend: {
		position: 'bottom',
		labels: {
			padding: 20,
			fontSize: 20,
		},
	},
	title: {
		display: true,
		position: 'bottom',
		fontSize: 30,
		text: country ? country : 'Worldwide',
	},
},
}

const chartCallback = (ChartJS) => {
ChartJS.plugins.register({
	beforeDraw: (chartInstance) => {
		const { chart } = chartInstance
		const { ctx } = chart
		ctx.fillStyle = 'white'
		ctx.fillRect(0, 0, chart.width, chart.height)
	},
})
ChartJS.plugins.register(ChartDatalabels)
}

const chart = new ChartJSNodeCanvas({ width: 720, height: 720, chartCallback })
return await chart.renderToBuffer(configChartJS).catch(err => console.log(err))
```

The first time I call my function to render the image, it works fine, but from the second time, it's always returning this error:

```
(node:11264) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of null
    at orient (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:157:19)
    at Object.fallback [as positioner] (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:381:13)
    at coordinates (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:849:21)
    at Object.draw (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:1013:18)
    at Object.afterDatasetsDraw (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-plugin-datalabels/dist/chartjs-plugin-datalabels.js:1332:12)
    at Object.notify (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:8032:16)
    at Chart.drawDatasets (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9917:16)
    at Chart.draw (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9845:6)
    at Chart.render (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9808:7)
    at Chart.update (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9681:7)
    at Chart.construct (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9374:6)
    at new Chart (/home/arahiko/Hanekawa-discord-bot/node_modules/chart.js/dist/Chart.js:9311:7)
    at ChartJSNodeCanvas.renderChart (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-node-canvas/dist/new.js:189:16)
    at ChartJSNodeCanvas.renderToBuffer (/home/arahiko/Hanekawa-discord-bot/node_modules/chartjs-node-canvas/dist/new.js:77:28)
    at getCovidTodayChart (/home/arahiko/Hanekawa-discord-bot/utils/chart.js:198:21)
    at Object.execute (/home/arahiko/Hanekawa-discord-bot/commands/utility/covid.js:43:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
This problem just happen with pie chart, others work fine

**Comment by SeanSobey** [comment]
Hi, 

With the code you have provided this seems most likely the same or similar to #9. You can have a read through there for the details but the short version is you need to persist the `ChartJSNodeCanvas` instance and let your `config` be in the same scope as the render call, eg `renderToBuffer`. This is quite a rare issue and as this lib sits in the middle of many other layers its difficult to isolate.

Give it a try and see if that resolves your issue.

**Comment by arahiko-ayami** [comment]
Hi, thanks for replying

I read the issue you sent, but it didn't work in my case. So I tried to replace constructor of `ChartJSNodeCanvas`  with this:

```Javascript
const chart = new ChartJSNodeCanvas({ width: 720, height: 720 })
```
It worked so I don't think the problem was made because of `config` scope, it was made because of my `chartCallback`. But I don't want to use to render a chart without background and datalabels

And the code I provided above still works if I rollback to `chart.js: 2.7.3` . I know it's hard to deeply understand where is the problem really is, so take your time.

**Comment by SeanSobey** [comment]
Ah ok, had a look at your callback and think I saw the issue. You are manually loading the DataLabels plugin, this is most likely causing scope and lifecycle issues. Try using the [built in](https://github.com/SeanSobey/ChartjsNodeCanvas#loading-plugins) method and see if that fixes your issue

**Comment by SeanSobey** [comment]
*Closed by mistake

**Comment by arahiko-ayami** [comment]
Thanks, follow what you said, I did this:

```Javascript
const chartCallback = (ChartJS) => {
ChartJS.plugins.register({
	beforeDraw: (chartInstance) => {
		const { chart } = chartInstance
		const { ctx } = chart
		ctx.fillStyle = 'white'
		ctx.fillRect(0, 0, chart.width, chart.height)
	},
   })
}

const chart = new ChartJSNodeCanvas({ width: 720, height: 720, chartCallback, plugins: { modern: ['chartjs-plugin-datalabels'] } })
```
It looks a little weird but it worked. So I just need do refactor work. I think my problem solved, so I'm going to close it. Anyway, thanks for helping me
